# Generated by Django 2.1.2 on 2018-10-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Изображение продукта')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Детальное описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Текущая цена')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Старая цена')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Скида')),
                ('new_product', models.BooleanField(default=False, verbose_name='Новый товар')),
                ('storage', models.PositiveIntegerField(default=0, verbose_name='Остатки на складе')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory'),
        ),
    ]
