# Generated by Django 2.1.8 on 2019-04-17 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190416_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 18, 7, 57, 220971, tzinfo=utc)),
        ),
    ]
