# Generated by Django 2.1.8 on 2019-04-21 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20190421_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 19, 10, 54, 862225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=512, verbose_name='VK страница'),
        ),
    ]
